# Generated by Django 5.1.4 on 2025-02-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preamble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Preamble", max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=models.TextField(),
        ),
    ]
