# Generated by Django 5.1.4 on 2025-02-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0002_preamble_alter_notice_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective", models.TextField()),
            ],
        ),
    ]
