# Generated by Django 5.1.4 on 2025-02-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0003_programobjective"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=200)),
                ("experience", models.TextField()),
                ("image", models.ImageField(upload_to="faculty_images/")),
            ],
        ),
    ]
