# Generated by Django 5.1.4 on 2025-02-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0004_faculty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name_plural": "Faculty"},
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={"verbose_name_plural": "Notices"},
        ),
        migrations.AlterModelOptions(
            name="preamble",
            options={"verbose_name_plural": "Preamble"},
        ),
        migrations.AlterModelOptions(
            name="programobjective",
            options={"verbose_name_plural": "Program Objectives"},
        ),
        migrations.AlterField(
            model_name="faculty",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="faculty/"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="qualification",
            field=models.CharField(max_length=255),
        ),
    ]
