# Generated by Django 5.1.4 on 2025-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0005_alter_faculty_options_alter_notice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="notices/"),
        ),
    ]
