# Generated by Django 5.1.4 on 2025-02-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0006_notice_link_notice_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
    ]
