# Generated by Django 5.1.4 on 2025-03-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0007_aboutpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=9)),
                ("title", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=20)),
                ("file", models.FileField(upload_to="syllabus/")),
            ],
            options={
                "verbose_name_plural": "Syllabi",
            },
        ),
        migrations.AlterModelOptions(
            name="aboutpage",
            options={"verbose_name_plural": "About Page"},
        ),
    ]
