# Generated by Django 5.1.4 on 2025-03-01 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0009_semester_eresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="eresource",
            options={"verbose_name_plural": "E-Resources"},
        ),
        migrations.RemoveField(
            model_name="syllabus",
            name="year",
        ),
        migrations.AddField(
            model_name="syllabus",
            name="academic_year",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cms_app.academicyear",
            ),
            preserve_default=False,
        ),
    ]
