# Generated by Django 5.1.4 on 2025-03-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0010_academicyear_alter_eresource_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="syllabus",
            options={},
        ),
        migrations.RemoveField(
            model_name="academicyear",
            name="year",
        ),
        migrations.AddField(
            model_name="academicyear",
            name="name",
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syllabus_set",
                to="cms_app.academicyear",
            ),
        ),
    ]
