# Generated by Django 5.1.4 on 2025-03-04 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0011_alter_syllabus_options_remove_academicyear_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syllabus",
            name="semester",
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syllabi",
                to="cms_app.academicyear",
            ),
        ),
    ]
