# Generated by Django 5.1.4 on 2025-03-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0013_syllabus_semester"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="syllabus",
            options={"verbose_name_plural": "Syllabi"},
        ),
    ]
