# Generated by Django 5.1.4 on 2025-03-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0014_alter_syllabus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=20, unique=True)),
                ("total_students", models.IntegerField()),
                ("students_placed", models.IntegerField()),
                ("higher_studies", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
