# Generated by Django 5.1.4 on 2025-03-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0015_placementrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About the Program", max_length=255),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
