# Generated by Django 5.1.4 on 2025-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0016_aboutprogram"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="recruiter_logos/")),
            ],
        ),
        migrations.RemoveField(
            model_name="placementrecord",
            name="higher_studies",
        ),
        migrations.AddField(
            model_name="placementrecord",
            name="pursuing_higher_studies",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="placementrecord",
            name="academic_year",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="placementrecord",
            name="students_placed",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="placementrecord",
            name="total_students",
            field=models.PositiveIntegerField(),
        ),
    ]
