# Generated by Django 5.1.4 on 2025-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0017_jobprofile_recruiter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("profile_image", models.ImageField(upload_to="alumni_images/")),
                ("current_position", models.CharField(max_length=255)),
                ("batch", models.CharField(max_length=10)),
                ("review", models.TextField(blank=True, null=True)),
                ("advice", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
