# Generated by Django 5.1.4 on 2025-03-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0018_alumni"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("class_name", models.CharField(max_length=50)),
                ("roll_no", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "cms_app_student",
            },
        ),
    ]
