# Generated by Django 5.1.4 on 2025-03-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0019_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FY", "First Year"),
                            ("SY", "Second Year"),
                            ("TY", "Third Year"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LectureTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="timetables/lecture/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_app.studentclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="timetables/exam/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_app.studentclass",
                    ),
                ),
            ],
        ),
    ]
