# Generated by Django 5.1.4 on 2025-03-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0020_studentclass_lecturetimetable_examtimetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclass",
            name="name",
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
