# Generated by Django 5.1.4 on 2025-03-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0021_alter_studentclass_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="reset_token",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
