# Generated by Django 5.1.4 on 2025-03-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0022_student_reset_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "proof",
                    models.FileField(blank=True, null=True, upload_to="leave_proofs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Denied", "Denied"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("admin_remarks", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="cms_app.student",
                    ),
                ),
            ],
        ),
    ]
