# Generated by Django 5.1.4 on 2025-03-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0023_leaveapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustrialVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=10)),
                ("duration", models.CharField(max_length=50)),
                ("batch_size", models.IntegerField()),
            ],
            options={
                "verbose_name": "Industrial Visit",
                "verbose_name_plural": "Industrial Visits",
            },
        ),
        migrations.CreateModel(
            name="VisitDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="cms_app.industrialvisit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="industrial_visits/")),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cms_app.industrialvisit",
                    ),
                ),
            ],
        ),
    ]
